vitruv-tools/Vitruv-Domains-ComponentBasedSystems

bundles/uml/tools.vitruv.domains.sysml/src/tools/vitruv/domains/sysml/tuid/SysMlToUmlResolver.xtend
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/tuid/UmlTuidCalculatorAndResolver.xtend

The new dispatch methods for `FlowProperty`, `ProfileApplication` and `ConnectorEnd` are needed for the TUID calculation in the automotive application.

Add dispatch methods

---

bundles/java/tools.vitruv.domains.java.echange/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.echange/metamodel/JavaEChange.genmodel
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/FeaturePackage.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/attribute/AttributePackage.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/attribute/impl/AttributePackageImpl.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/impl/FeaturePackageImpl.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/impl/JavaFeatureEChangeImpl.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/reference/ReferencePackage.java
bundles/java/tools.vitruv.domains.java.echange/src-gen/tools/vitruv/domains/java/echange/feature/reference/impl/ReferencePackageImpl.java
bundles/java/tools.vitruv.domains.java.monitorededitor/src/tools/vitruv/domains/java/monitorededitor/MonitoredEditor.java
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/tuid/JavaTuidCalculatorAndResolver.xtend

This PR adapts the Domains to the introduction of UUIDs in the Vitruv framework.
It especially adapts the Java-specific change descriptions metamodel.
Additionally, it extends the `JavaTuidCalculatorAndResolver` to correctly handle the cases introduced by completely unresolving and reapplying changes.

UUIDs Mapping

---

bundles/emfprofiles/tools.vitruv.domains.emfprofiles/build.properties
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JavaDomain.xtend
bundles/pcm/tools.vitruv.domains.pcm/src/tools/vitruv/domains/pcm/PcmDomain.xtend
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/UmlDomain.xtend

This PR adds an operation to the Java, PCM and UML domain to manually enable transitive change propagation, which is disabled per default. This can be used for test cases examining transitive change propagation based on Reactions.

Allow transitive change propagation

---

bundles/uml/tools.vitruv.domains.uml/META-INF/MANIFEST.MF
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/Activator.java
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/UmlDomain.xtend

This PR fixes an issue that caused the first test (and potentially also first modification in live models) to fail.
This was due to the reason that the UmlDomain registered our modified UMLResource that does not use the outdated XMI-IDs. Nevertheless, if the `ResourceSet` was already created before calling the domain the first time, the `ResourceSet` used the old resource. To avoid that, this PR adds a bundle activator that already registers the modified domain on startup.

Register modified UML resource on startup instead of lazy

---

pom.xml
releng/tools.vitruv.domains.updatesite.aggregated/updatesite.aggr

Since the EMFText udpatesite is unavailable for some days, we deployed a dump to the kit-sdq updatesite, which we refer to now in the domains to make the build work again.

Change EMFText dependency to dump due to unavailability of updatesite

---

bundles/emfprofiles/tools.vitruv.domains.emfprofiles/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor.astchangelistener/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor.astchangelistener/plugin.xml
bundles/java/tools.vitruv.domains.java.monitorededitor.changeclassification/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor.javamodel2ast/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor.methodchange/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor.refactoringlistener/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java.monitorededitor/plugin.xml
bundles/java/tools.vitruv.domains.java/META-INF/MANIFEST.MF
bundles/uml/tools.vitruv.domains.sysml/META-INF/MANIFEST.MF
bundles/uml/tools.vitruv.domains.uml/META-INF/MANIFEST.MF

This PR adds missing declarations of package exports (internal or not) marked as warnings in current Eclipse versions.
Additionally, it corrects two extension point specifications of the Java domain.

Complete export declarations

---

bundles/java/tools.vitruv.domains.java.util/src/tools/vitruv/domains/java/util/JavaPersistenceHelper.xtend

Fixed problem with the persistence of Java packages, which lead to invalid Java changes and as a result of the consistency preservation to duplicate UML packages. Unnamed Java packages produced a path that contained an empty segment (`//`) instead of a name, which then leads to applying changes, such as rename changes, to the parent package of the unnamed package. The empty segment was being ignored, and the resulting path matches the parent package: E.g. `/foo//` instead of `/foo/bar/`. These invalid changes propagated to the UML model and resulted in duplicate package names.
This problem was fixed by replacing the empty segment by any non-empty string (e.g. `//` => `/unnamedPackage/`). This placeholder is later replaced when the Java package is renamed.

Fixed problem with unnamed Java packages & empty path segments

---

bundles/java/tools.vitruv.domains.java/META-INF/MANIFEST.MF
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JamoppLibraryHelper.xtend
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JavaDomain.xtend

JaMoPP is not able to resolve the standard library using Java 9 and above. The library is not placed in the JRE folder anymore but provided in terms of modules.
We resolve that issue by adding the new path to the module library in the Java domain and overwriting the load mechanisms, as packaging is different in Java 9 and above (there is a folder prefix in the packaged file that has to be ignores for the class names).
This PR fixes issue #45.

Extend standard library loading in JaMoPP to support Java 9

---

.mvn/extensions.xml
releng/tools.vitruv.domains.cbs.parent/pom.xml
releng/tools.vitruv.domains.cbs.updatesite.aggregated/updatesite.aggr

This PR upgrades the parent POM version to 0.7.0, which improves dependencies to Eclipse 2020-06.
It also removes the updatesite category for demo metamodels, which is now provided by the framework updatesite, because the demo applications are part of the framework and not the CBSE case study.

Eclipse 2020-06

---

bundles/confidentiality/tools.vitruv.domains.confidentiality/src/tools/vitruv/domains/confidentiality/ConfidentialityDomainProvider.xtend
bundles/emfprofiles/tools.vitruv.domains.emfprofiles/src-test/tools/vitruv/domains/emfprofiles/EmfProfilesDomainTest.xtend
bundles/emfprofiles/tools.vitruv.domains.emfprofiles/src/tools/vitruv/domains/emfprofiles/EmfProfilesDomainProvider.xtend
bundles/java/tools.vitruv.domains.java.util/src/tools/vitruv/domains/java/util/JavaModificationUtil.xtend
bundles/java/tools.vitruv.domains.java.util/src/tools/vitruv/domains/java/util/JavaPersistenceHelper.xtend
bundles/java/tools.vitruv.domains.java/src-test/tools/vitruv/domains/java/JavaDomainTests.xtend
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JamoppLibraryHelper.xtend
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JavaDomain.xtend
bundles/java/tools.vitruv.domains.java/src/tools/vitruv/domains/java/tuid/JavaTuidCalculatorAndResolver.xtend
bundles/pcm/tools.vitruv.domains.pcm/src-test/tools/vitruv/domains/pcm/PcmDomainTests.xtend
bundles/pcm/tools.vitruv.domains.pcm/src/tools/vitruv/domains/pcm/PcmDomain.xtend
bundles/uml/tools.vitruv.domains.sysml/src-test/tools/vitruv/domains/sysml/SysMlDomainTests.xtend
bundles/uml/tools.vitruv.domains.sysml/src/tools/vitruv/domains/sysml/SysMlDomainProvider.xtend
bundles/uml/tools.vitruv.domains.sysml/src/tools/vitruv/domains/sysml/tuid/SysMlToUmlResolver.xtend
bundles/uml/tools.vitruv.domains.sysml/src/tools/vitruv/domains/sysml/tuid/SysMlTuidCalculatorAndResolver.xtend
bundles/uml/tools.vitruv.domains.uml/src-test/tools/vitruv/domains/uml/UmlDomainTests.xtend
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/UmlDomain.xtend
bundles/uml/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/UmlDomainProvider.xtend

This PR removes several unnecessary modifiers in Xtend code, which resolves code style warnings in the Xtend default settings in Eclipse.

Remove unnecessary modifiers

---

bundles/java/tools.vitruv.domains.java.builder/src/tools/vitruv/domains/java/builder/JavaBuildOnEclipseStartup.java
bundles/java/tools.vitruv.domains.java.monitorededitor/src/tools/vitruv/domains/java/monitorededitor/MonitoredEditor.java

- Adapt to changed method signature for incremental project build
- Refresh projects before performing change propagation in `MonitoredEditor` for Java code
- Log errors during change propagation in `MonitoredEditor` for Java code, which were swallowed before

Incremental build and project refresh

---

bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/monitorededitor/JavaMonitoredEditor.xtend

Processing a change event must be possible without locking the `JavaMonitoredEditor`. Otherwise a change propagation may be running (which needs to lock the `JavaMonitoredEditor`), but since it is run within a build `Job`, it in turn waits for the resource change `Job` to finish, which cannot proceed as it waits for the lock acquired by the change propagation `Job`. This is a classical deadlock.
In fact, we have used locking to avoid that multiple change processing or change propagation processes / jobs are running at the same time, whereas it should be specifically used to avoid race conditions and ensure memory consistency. This PR reduces the synchronization to what is absolutely necessary.

Avoid Locks in Java Monitored Editor to Allow Multiple Jobs Accessing It

---

bundles/tools.vitruv.domains.emfprofiles/.classpath
bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/builder/VitruvJavaBuilder.java
bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/monitorededitor/JavaMonitoredEditor.xtend

Fixes a bug that caused an exception when checking a project builder for being alive because of not checking project for being open.

Fix Bug in Builder Aliveness Check

---

bundles/pom.xml
bundles/tools.vitruv.domains.emfprofiles/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.java.echange/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.java.ui.methodchange/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.java.ui/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.java/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.pcm/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.sysml/META-INF/MANIFEST.MF
bundles/tools.vitruv.domains.uml/META-INF/MANIFEST.MF
features/pom.xml
features/tools.vitruv.domains.emfprofiles.feature/feature.xml
features/tools.vitruv.domains.java.feature/feature.xml
features/tools.vitruv.domains.pcm.feature/feature.xml
features/tools.vitruv.domains.sysml.feature/feature.xml
features/tools.vitruv.domains.uml.feature/feature.xml
pom.xml
releng/tools.vitruv.domains.cbs.parent/pom.xml
releng/tools.vitruv.domains.cbs.updatesite.aggregated/pom.xml
releng/tools.vitruv.domains.cbs.updatesite.aggregated/updatesite.aggr
releng/tools.vitruv.domains.cbs.updatesite/category.xml
releng/tools.vitruv.domains.cbs.updatesite/pom.xml
tests/pom.xml
tests/tools.vitruv.domains.java.ui.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.domains.java.ui.tests/pom.xml

This PR releases version 2.0.0 and increases the development version 2.1.0.
We have made API-breaking changes in both reexported packages of the framework (which also upgraded from 1.0.0 to 2.0.0) as well as in the domains themselves. This especially concerns the completely restructured Java domain.

Release 2.0.0

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/util/JavaModificationUtil.xtend

The resolve logic for concrete classifiers was evil: It resulted in models referencing model objects from other resource sets. Plus, made caching references to types impossible, because they were resolved in a new resource set on every request. That already led to performance degradation in tests. In production, however, the performance hit would be even worse, because there we have long-lived resource sets (as opposed to the short-lived in tests), were caching would really make all the difference.
:warning: This PRs should be merged _after_ https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/128 :warning:

Do not Resolve Java Types in Foreign Resource Sets

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/util/JavaPersistenceHelper.xtend

This PR prepares for https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/129 to correctly treat the `name` of a Java `CompilationUnit` as a fully qualified name.
The applications will break with these changes and properly run again after merging https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/129.

Correctly Treat Java Compilation Unit Name as FQN

---

releng/tools.vitruv.domains.cbs.updatesite.aggregated/updatesite.aggr

Adds Eclipse as mapped repository to aggregated updatesite to enable resolution of referenced artifacts when setting up target platform.

Eclipse as Mapped Repository in Aggregated Updatesite

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/util/JavaModificationUtil.xtend

Adapts to the `VURI` removal in https://github.com/vitruv-tools/Vitruv/pull/457
But can be merged before, as it does not depend on the removal.

Adapt to VURI Removal

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/util/JavaModificationUtil.xtend

Reverts #100 because of an unfixed incompatibility with the CBS applications (see comment in https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/pull/100#issuecomment-812120806).

Revert #100

---

.github/workflows/applicationsvalidation.yml

Perform application validation on every pull request to avoid cases like in #101.
Like in the framework repository application validation, uses the branch matching the current branch name in the application's repository (if any), otherwise the master branch. Always uses the framework master branch to enforce merge order framework -> domains -> applications.

Perform applications validation on pull request

---

bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/monitorededitor/JavaMonitoredEditor.xtend

Adapts to removal of domain-aware resources/resource sets in https://github.com/vitruv-tools/Vitruv/pull/468.

Adapt to Removal of Domain-Aware Resource Sets

---

.mvn/extensions.xml
.mvn/wrapper/maven-wrapper.properties
releng/tools.vitruv.domains.cbs.parent/pom.xml
releng/tools.vitruv.domains.cbs.updatesite.aggregated/updatesite.aggr

Increases parent POM version to 1.3.0 (Eclipse 2021-06) and increases PCM dependency to 5.0.0 (latest release).

Eclipse 2021-06

---

releng/tools.vitruv.domains.cbs.parent/pom.xml
releng/tools.vitruv.domains.cbs.updatesite.aggregated/updatesite.aggr

Upgrades to Eclipse 2021-12 (parent POM 1.4.0) and changes updatesite URLs from http to https.

Eclipse 2021-12

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/util/JavaPersistenceHelper.xtend

This allows to pass any kind of `JavaRoot` to the method for retrieving the according file path, thus allowing generic handling of all kinds of `JavaRoot` elements in persistence logic.

Use dynamic dispatch for file path creation of Java root elements

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JamoppLibraryHelper.xtend

Add functionality for loading further modules of the Java standard library and of local libraries to be used within a (test) project.

Extend functionality of JaMoPP helper for loading libraries

---

bundles/tools.vitruv.domains.java/src/tools/vitruv/domains/java/JavaDomain.xtend
bundles/tools.vitruv.domains.pcm/src/tools/vitruv/domains/pcm/PcmDomain.xtend
bundles/tools.vitruv.domains.uml/src/tools/vitruv/domains/uml/UmlDomain.xtend

Adds methods for disabling transitive change propagation in the Java, UML and PCM domain.
This, in particular, allows to dynamically disable and enable transitive change propagation in tests.

Add functionality for disabling transitive change propagation

---

bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/monitorededitor/JavaMonitoredEditor.xtend

Supporting PR for [Vitruv#492](https://github.com/vitruv-tools/Vitruv/pull/492)
Replaces the state-based VSUM API access in the `JavaMonitoredEditor` by manually generating the changes based on the initial and changed view state and then propagating them using the delta-based VSUM API. 
The proposed solution should be considered only a workaround to avoid the state-based API and not a perfectly clean solution. This is due to the fact that the Java editor (as any editor) should be attached to a view and reuse its functionality instead of working on the internal files directly. However, this is out of scope for this PR.

Move state-based propagation to views

---

.github/workflows/applicationsvalidation.yml
releng/tools.vitruv.domains.cbs.parent/pom.xml

This PR adds a local build Maven profile as described in [Vitruv#510](https://github.com/vitruv-tools/Vitruv/issues/510).
While the simpler solution would have been to not use a profile but rather only the `vitruv.framework.url` property, this would have required from the user to include the entire url `file://<path_to_vitruv_folder>/releng/tools.vitruv.updatesite.aggregated/target/final` when calling. I chose to integrate a profile such that only the path to the Vitruv directory, instead of to the actual update site, can be provided. If the update site is at the expected relative path in the Vitruv folder, one can still customize the entire url by calling `-Dvitruv.framework.url='<url>'`.
`mvn clean verify -Dvitruv.framework.path='<path_to_vitruv_folder>'`
⚠️ Requires …

Add local build Maven profile

---

releng/tools.vitruv.domains.cbs.parent/pom.xml

Corrects the file URI scheme used in the parent pom to use a local repository
Previous `file://`, now `file:///`
[File URI scheme description](https://en.wikipedia.org/wiki/File_URI_scheme)

Correct file URI in parent pom

---

releng/tools.vitruv.domains.cbs.parent/pom.xml

Removes the explicit version in the updatesite URL for the SDQ Commons dependencies to ensure that always the latest available version is used.

Remove explicit version from dependency updatesite

---

releng/tools.vitruv.domains.cbs.parent/pom.xml

This PR adds a property for the changes updatesite repository, such that it can be referenced in a local build of that site.
It also remove the unnecessary aggregated updatesite of Vitruv.

Add changes updatesite and path parameter

---

bundles/tools.vitruv.domains.java.ui/src/tools/vitruv/domains/java/ui/monitorededitor/JavaMonitoredEditor.xtend

This PR adapts to the unified names of project and package names of the change projects in vitruv-tools/Vitruv-Change#7.

Adapt to modified composite change project name
